name: Generate TypeScript Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Instantiate package
        uses: actions/checkout@v3

      - name: Install
        run: npm ci

      - name: Generate typedoc
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
